---
- name: start icinga2
  become: yes
  systemd:
    name: icinga2
    state: started
    enabled: yes

- name: reload icinga2
  become: yes
  systemd:
    name: icinga2
    state: reloaded

- name: restart icinga2
  become: yes
  systemd:
    name: icinga2
    state: restarted

- name: restart php-fpm
  become: yes
  systemd:
    name: php{{php_version}}-fpm
    state: restarted

- name: restart graphite
  become: yes
  systemd:
    name: graphite-api
    state: restarted

- name: restart carbon-cache
  become: yes
  systemd:
    name: carbon-cache
    state: restarted

- name: restart graphite-uwsgi
  become: yes
  systemd:
    name: uwsgi
    state: restarted

- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  become: yes
  systemd:
    name: nginx
    state: reloaded
