---
- hosts: cityhall
  gather_facts: false

  vars_prompt:
    - name: 'mattermost_sites'
      prompt: 'Site hostnames, space separated if more than one'
      default: 'mattermost.site.co mm.site2.co'
      private: no

    - name: 'mattermost_feedback_email'
      prompt: 'What is you Mattermost feedback email?'
      default: 'mattermost@site.co'
      private: no

    - name: 'mattermost_enterprise'
      prompt: 'Install Mattermost Enterprise Version (y/n)?'
      default: 'n'
      private: no

    - name: 'mattermost_use_letsencrypt'
      prompt: 'Use Letencrypt (y/n)?'
      default: 'n'
      private: no

  tasks:
    - name: generate random strings for passwords
      local_action: shell < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c {{ item.size }}
      register: rand_result
      loop:
        - { size: '{{25|random(20,1)}}' }
        - { size: '{{40|random(30,1)}}' }
        - { size: '{{40|random(30,1)}}' }
        - { size: '{{40|random(30,1)}}' }

    - set_fact:
        mattermost_postgresql_password: "{{ rand_result.results[item].stdout }}"
      with_random_choice:
        - 0
        - 1

    - name: create group_vars/mattermost_server.yml
      template:
        src: roles/mattermost/templates/mattermost_server.yml.j2
        dest: config/group_vars/mattermost_server.yml

    - debug:
        msg: "You can now edit group_vars/mattermost_server.yml and add server to the inventory"
