---
- hosts: cityhall
  gather_facts: false

  vars_prompt:
    - name: 'mumble_sites'
      prompt: 'Site hostnames, space separated if more than one'
      default: 'mumble.site.co meet.site2.co'
      private: no

    - name: 'mumble_password'
      prompt: 'What is you Mumble global password?'
      private: yes

  tasks:
    - name: generate random strings for passwords
      local_action: shell < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c {{ item.size }}
      register: rand_result
      loop:
        - { size: '{{25|random(20,1)}}' }
        - { size: '{{40|random(30,1)}}' }

    - set_fact:
        mumble_superuser_pass: "{{ rand_result.results[item].stdout }}"
      with_random_choice:
        - 0
        - 1

    - name: create group_vars/mumble_server.yml
      template:
        src: roles/mumble/templates/mumble_server.yml.j2
        dest: config/group_vars/mumble_server.yml

    - debug:
        msg: "You can now edit group_vars/mumble_server.yml and add server to the inventory"
