---
- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: create tmpfiles
  become: true
  command: /bin/systemd-tmpfiles --create

- name: slapd enable
  become: true
  systemd:
    name: slapd.service
    state: started
    enabled: yes

- name: slapd restart
  become: true
  systemd:
    name: slapd.service
    state: restarted
  register: slapdrestart
