---
# these 2 roles add the autodeflect vars if setup, ie; dnets
- name: check if autodeflect is configured
  become: yes
  local_action:
    module: stat
    path: "{{deflect_controller_root}}/modules/autodeflect/config/group_vars/controller.yml"
  run_once: yes
  register: ad_controller_file
  tags:
    - always

- name: autodeflect controller variables
  become: yes
  include_vars: "{{deflect_controller_root}}/modules/autodeflect/config/group_vars/controller.yml"
  when: "(ad_controller_file.stat.readable | default(false))"
  tags:
    - always

- include_tasks: icinga2.yml
  tags:
    - always

- include_tasks: scripts.yml
  tags:
    - always
