---
- name: Copy helper scripts
  become: true
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: '0550'
  loop:
    - slapd-attribute-upsert
    - slapd-create-monitor
    - slapd-create-overlay
    - slapd-olc-attribute-clean
    - slapd-global-modules
    - slapd-global-schema
    - slapd-mdb-create
    - slapd-overlay-attribute-upsert
    - slapd-overlay-dn
    - slapd-overlay-olc-attribute-clean
    - slapd-password-hash

- name: if we have certs then install
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ slapd_conf_dir }}/certs/{{ item | basename }}"
    owner: "{{ slapd_user }}"
    group: "{{ slapd_group }}"
    mode: '0600'
  loop:
    - config/ldap/certs/ldap-ca-key.pem
    - config/ldap/certs/ldap-ca-cert.pem
  failed_when: false
  tags:
    - ldap_certs

# Global
- include: global-schemas.yml
- include: global-config.yml
- include: global-modules.yml
# Frontend
- include: frontend-config.yml
# OLC
- include: olc-config.yml
# Monitor
- include: monitor-create.yml
  when: slapd_enable_monitor
- include: monitor-config.yml
  when: slapd_enable_monitor
# MDB
- include: mdb-create.yml
- include: mdb-overlay-create.yml
  with_dict: "{{ slapd_mdb_overlays }}"
  when: "slapd_mdb_overlays is not undefined"
- include: mdb-overlay-config.yml
  with_dict: "{{ slapd_mdb_overlays }}"
  when: "slapd_mdb_overlays is not undefined"
- include: mdb-config.yml
