---
- name: "Create {{ item.key }} Overlay"
  become: true
  command: >
    /usr/local/bin/slapd-create-overlay "{{ slapd_ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ slapd_olc_rootdn }}"
    "olcDatabase={2}mdb,cn=config"
    "{{ item.key }}"
    {% for dict in item.value %}
    {% for key, value in dict.items() %}
    "{{ key }}: {{ value }}"
    {% endfor %}
    {% endfor %}
  environment:
    bindpw: "{{ slapd_olc_rootdn_password | mandatory }}"
  register: out
  changed_when: "'CHANGED' in out.stdout"
